volumes:
  local_app_data: {}

services:
  app: &app
    build:
      context: .
      dockerfile: ./compose/local/go/Dockerfile
      target: dev
    ports:
      - 8080:8080
    volumes:
      - local_app_data:/usr/src/app
    image: local_app
    depends_on:
      - redis
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
