volumes:
  local_app_data: {}

services:
  app: &app
    build:
      context: .
      dockerfile: ./compose/prod/go/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - local_app_data:/usr/src/app
    image: local_app
    depends_on:
      - redis
    environment:
      - SERVER_TIMEOUT=30000
      - SERVER_ADDR=:8080
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
